database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.cj.jdbc.Driver
  # the username
  user: iipsen2
  # the password
  password: IIpsen2OMgeving
  # the JDBC URL; the database is called DWGettingStarted
  url: jdbc:mysql://145.131.5.100/iipsen2?serverTimezone=UTC&useSSL=false
  validationQuery: "/* MyService Health Check */ SELECT 1"